{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: TurBoNC
  version: v0.0.1
  author: TurBoss
  description: Just the basic functions I need to run linuxcnc

data_plugins:
  status:
    kwargs:
      cycle_time: 75

  persistent_data_manager:
    provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
    kwargs:
      # serialization method to use: json or pickle
      serialization_method: pickle
      # persistence_file: .vcp_data.json

  settings:
    provider: qtpyvcp.plugins.settings:Settings

  position:
    provider: qtpyvcp.plugins.positions:Position
    kwargs:
      report_actual_pos: True
      use_program_units: True

  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable

  clock:
    provider: qtpyvcp.plugins.clock:Clock
#
#  api:
#    provider: qtpyvcp.plugins.api:VcpApi

windows:
  mainwindow:
    provider: tnc.main:MainWindow
    kwargs:
      menu: ( default_menubar )
      ui_file: {{ file.dir }}/ui/window.ui

application:
  kwargs:
    stylesheet: {{ file.dir }}/style.qss
